// Generated from src/plugins/helpers.mjs by build.sh — do not edit this file.

/**
 * Helpers plugin — additional formula helpers beyond the bundled set.
 *
 * The bundled helpers (alias, add, subtract, multiply, divide) are
 * registered automatically by initEngine. This plugin provides
 * domain-specific helpers that documents opt into explicitly.
 *
 * Adding a new helper requires only a new `registry.registerHelper`
 * call here — no other files need changing.
 *
 * @module plugins/helpers
 */
//
// ── Helpers plugin ─────────────────────────────────────────────────────────
//
// Canonical source. Edit this file.
// global/helpers.js is generated from this file by build.sh — do not edit it.


/** @type {Record<string, string>} */
const specialCharsMap = {
  ä: "ae",
  ö: "oe",
  ü: "ue",
  ß: "ss",
  Ä: "Ae",
  Ö: "Oe",
  Ü: "Ue",
};

const specialCharsRegex = new RegExp(
  `[${Object.keys(specialCharsMap).join("")}]`,
  "g",
);

/**
 * Initialises the helpers plugin by registering additional helpers.
 * @returns {void}
 */
function initHelpers() {

  // Joins args with a separator (default "-") and slugifies the result.
  // Configurable via data-separator on the output element.
  registry.registerHelper("slugify", (args, dataset) => {
    const separator = dataset.separator ?? "-";
    return args
      .join(separator)
      .toLowerCase()
      .trim()
      .replace(specialCharsRegex, (char) => specialCharsMap[char])
      .replace(/[^\w\s-]/g, "")
      .replace(/[\s_]+/g, separator);
  });

}

