#!/bin/sh
# ---
# name: build
# description: generates explorable/global/ from explorable/src/.
# usage: sh build.sh
# exits:
#   0: always
# ---

SRC="src"
GLOBAL="global"

# Files to exclude from the global build (paths relative to SRC).
EXCLUDED="core.mjs types.js"

mkdir -p "$GLOBAL"

# find all .mjs files under src/, including subdirectories
find "$SRC" -name "*.mjs" | while read -r src_file; do

  # Compute path relative to SRC (e.g. "core/base.mjs" or "main.mjs")
  rel="${src_file#$SRC/}"

  # Derive output filename: replace .mjs extension with .js
  rel_js="${rel%.mjs}.js"

  # Skip excluded files
  skip=0
  for excl in $EXCLUDED; do
    if [ "$rel" = "$excl" ]; then
      skip=1
      break
    fi
  done
  if [ "$skip" = "1" ]; then
    echo "skipped: $src_file"
    continue
  fi

  out_file="$GLOBAL/$rel_js"

  # Ensure the output subdirectory exists
  mkdir -p "$(dirname "$out_file")"

  {
    echo "// Generated from src/${rel} by build.sh — do not edit this file."
    sed \
      -e '/^[[:space:]]*export[[:space:]]*{[^}]*}[[:space:]]*;*[[:space:]]*$/d' \
      -e '/^[[:space:]]*export[[:space:]][[:space:]]*default[[:space:]]/d' \
      -e '/^[[:space:]]*import[[:space:]]/d' \
      -e '/^\/\/[[:space:]]*@ts-check[[:space:]]*$/d' \
      "$src_file"
  } > "$out_file"

  echo "built: $out_file"
done
