// Generated from src/core/base.mjs by build.sh — do not edit this file.

/**
 * Base — value store and plugin registry.
 *
 * The shared foundation consumed by both the engine and the interaction layer.
 * Neither depends on the other — both depend on this.
 *
 * @module core/base
 */
//
// ── Base ───────────────────────────────────────────────────────────────────
//
// Canonical source. Edit this file.
// global/base.js is generated from this file by build.sh — do not edit it.

// ── Plugin registries ──────────────────────────────────────────────────────

/** @type {Record<string, function(Array<ExplorableValue>, DOMStringMap): ExplorableValue>} */
const _helpers = {};

/** @type {Formatter[]} */
const _formatters = [];

/** @type {InputHandler[]} */
const _inputHandlers = [];

/** @type {Visual[]} */
const _visuals = [];

/** @type {Record<string, function(ExplorableValue, ExplorableValue): boolean>} */
const _conditions = {};

// ── Registry (public) ──────────────────────────────────────────────────────

/** @type {Registry} */
const registry = {
  /**
   * Registers a helper function by name.
   * Called by the engine when evaluating `data-helper` on output elements.
   * Receives the dependency values as an array and the output's dataset.
   * @param {string} name
   * @param {function(Array<ExplorableValue>, DOMStringMap): ExplorableValue} fn
   * @returns {void}
   */
  registerHelper(name, fn) {
    _helpers[name] = fn;
  },

  /**
   * Registers a value formatter tied to a format type string.
   * Formatters control label and output text for elements carrying
   * `data-format="type:value"`.
   * @param {Formatter} formatter
   * @returns {void}
   */
  registerFormatter(formatter) {
    _formatters.push(formatter);
  },

  /**
   * Registers an input interaction handler.
   * Handlers are matched in registration order — first match wins.
   * @param {InputHandler} handler
   * @returns {void}
   */
  registerInputHandler(handler) {
    _inputHandlers.push(handler);
  },

  /**
   * Registers a visual tied to a data attribute on an input.
   * The render function receives the associated label element directly —
   * visuals always target the label, never the hidden input.
   * @param {Visual} visual
   * @returns {void}
   */
  registerVisual(visual) {
    _visuals.push(visual);
  },

  /**
   * Registers a condition operator for use in `data-condition` expressions.
   * @param {Condition} condition
   * @returns {void}
   */
  registerCondition(condition) {
    _conditions[condition.operator] = condition.evaluate;
  },
};

// ── Value store ────────────────────────────────────────────────────────────
//
// Single source of truth for all explorable values — inputs and computed
// outputs alike. The DOM is for display only; nothing reads values back
// out of it.

/** @type {Map<string, ExplorableValue>} */
const _values = new Map();

/** @type {Map<string, Set<SubscribeCallback>>} */
const _subscribers = new Map();

/** @type {Store} */
const store = {
  /**
   * Returns the current value for the given element ID.
   * Returns 0 if the ID has not been set.
   * @param {string} id
   * @returns {ExplorableValue}
   */
  get(id) {
    return _values.get(id) ?? 0;
  },

  /**
   * Registers a callback that fires whenever the value for `id` changes.
   * Returns an unsubscribe function.
   * @param {string} id
   * @param {SubscribeCallback} callback
   * @returns {Unsubscribe}
   */
  subscribe(id, callback) {
    if (!_subscribers.has(id)) _subscribers.set(id, new Set());
    /** @type {Set<SubscribeCallback>} */ (_subscribers.get(id)).add(callback);
    return () => /** @type {Set<SubscribeCallback>} */ (_subscribers.get(id)).delete(callback);
  },

  /**
   * Internal. Sets a value and notifies all subscribers.
   * Not intended for use by plugins.
   * @param {string} id
   * @param {ExplorableValue} value
   * @returns {void}
   */
  _set(id, value) {
    _values.set(id, value);
    _subscribers.get(id)?.forEach(cb => cb(value));
  },
};

// ── Formatter utilities ────────────────────────────────────────────────────
//
// Shared by engine (output formatting) and interaction (label formatting).

/**
 * Parses a `data-format` attribute value into type and config.
 * "currency:USD" → { type: "currency", value: "USD" }
 * "date"         → { type: "date", value: "" }
 * @param {string} attrValue
 * @returns {{ type: string, value: string }}
 */
function parseFormat(attrValue) {
  const [type, value = ""] = attrValue.split(":");
  return { type, value };
}

/**
 * Returns the formatter for a given element, or null if none applies.
 * @param {Element} elem
 * @returns {{ formatter: Formatter, value: string } | null}
 */
function getFormatter(elem) {
  const attr = elem.getAttribute("data-format");
  if (!attr) return null;
  const { type, value } = parseFormat(attr);
  const formatter = _formatters.find(f => f.type === type) ?? null;
  return formatter ? { formatter, value } : null;
}

/**
 * Returns true if any registered formatter claims this element.
 * @param {Element} elem
 * @returns {boolean}
 */
function isFormatted(elem) {
  if (!elem.hasAttribute("data-format")) return false;
  const { type } = parseFormat(elem.getAttribute("data-format") ?? "");
  return _formatters.some(f => f.type === type);
}

/**
 * Returns the nearest ancestor lang attribute, defaulting to "en".
 * @param {Element} elem
 * @returns {string}
 */
function getParentLang(elem) {
  return elem.closest("[lang]")?.getAttribute("lang") ?? "en";
}

